/**
 * The characteristics a character sheet already knows about itself.
 *
 * A sheet exported by **Ork HERO Templates** carries the numbers a game master
 * would otherwise type into the dialog by hand — SPD, DEX, REC, END, STUN and
 * BODY in one table, and the Lightning Reflexes that decides INIT in another. So
 * they are read off the file rather than transcribed from it.
 *
 * Only from a sheet that says it is one. The marker comment at the top of the
 * file is the whole of the licence to guess at somebody else's markup: without
 * it, ids like `characteristics-collapse` are just words that might mean this or
 * might mean anything, and a wrong reading here writes silently onto a character.
 * An unmarked sheet is left completely alone.
 *
 * Shared between the browser and the server because both fill a character in:
 * the dialog reads the file as it is chosen, and the server reads the stored
 * sheet for characters filed by dropping a folder of them, which send no fields
 * at all. One parser, so the two cannot disagree about what a sheet says.
 *
 * Text rather than a DOM. The parser has to run in both places, and this is how
 * `uploads.ts` already reads a sheet looking for the portrait inside it.
 */

import { HERO_STAT_FIELDS, HERO_STAT_LABELS, type HeroStatField } from "./hero.ts";

/**
 * What the generator stamps at the top of everything it writes.
 *
 * Matched inside the head of the file rather than anywhere in it: the phrase in
 * the comment is the sheet identifying itself, where the same words further down
 * could be a character called after the tool, or this app's own name quoted in
 * somebody's notes.
 */
const MARKER = "Generated by Ork HERO Templates";

/** How far in to look for it. The real sheets carry it inside 600 bytes. */
const MARKER_WINDOW = 4096;

/**
 * The talent that grants an initiative bonus, and the only form of it that
 * counts.
 *
 * `All Actions` is load-bearing. Lightning Reflexes can be bought for a single
 * kind of action — "+3 DEX to act first with Ranged attacks" — and that is not
 * an initiative bonus a fight can be ordered by, so it is not one this reads.
 *
 * `Lightning Calculator` is a different talent that shares the first word, and
 * is why this matches the whole phrase rather than the name.
 */
const LIGHTNING_REFLEXES = /Lightning Reflexes:\s*\+(\d+)\s+DEX to act first with All Actions/i;

/** The label each characteristic is written under, back to the field it fills. */
const FIELD_BY_LABEL = new Map<string, HeroStatField>(
  HERO_STAT_FIELDS.map((field) => [HERO_STAT_LABELS[field], field]),
);

/** A cell's text: tags out, entities that matter decoded, whitespace collapsed. */
function textOf(cell: string): string {
  return cell
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * The number a value cell says, or `null` where it does not say one.
 *
 * HERO writes some characteristics as a pair — `PD 6 / 16` is the base and what
 * it comes to with the armour on — and the first half is the characteristic
 * itself, which is what this app stores. So a cell is read up to the first
 * slash, and a cell with no slash in it is read whole.
 *
 * What is left has to be a whole number for the cell to count. That is what
 * still throws out the header row, the total row written back to front, the
 * fractions (`OCV 7.666…`) and the distances (`Leaping 6"/3"`, whose first half
 * is not a number either) — none of which is a value this app could store.
 */
function valueOf(cell: string): number | null {
  const head = cell.split("/", 1)[0]!.trim();
  return /^-?\d+$/.test(head) ? Number(head) : null;
}

/**
 * The rows of the first table inside the div with this id, each as its cells'
 * text.
 *
 * "The first table" is taken literally — from the opening tag to the first
 * closing one — which is exact here because neither of these divs nests a table
 * inside another, and is why this can be a scan rather than a parse. A div or a
 * table that is not there yields nothing, which every caller reads as "the sheet
 * does not say".
 */
function rowsOfFirstTable(html: string, id: string): string[][] {
  const div = html.indexOf(`id="${id}"`);
  if (div < 0) return [];

  const open = html.indexOf("<table", div);
  if (open < 0) return [];

  const close = html.indexOf("</table>", open);
  if (close < 0) return [];

  const table = html.slice(open, close);
  return [...table.matchAll(/<tr[^>]*>(.*?)<\/tr>/gs)].map((row) =>
    [...row[1]!.matchAll(/<t[dh][^>]*>(.*?)<\/t[dh]>/gs)].map((cell) => textOf(cell[1]!)),
  );
}

/**
 * What a sheet says its character's characteristics are, as far as it says
 * anything.
 *
 * A field missing from the result is one the sheet did not give a usable answer
 * for, and callers leave those alone. The exception is INIT, which a marked sheet
 * always answers: no Lightning Reflexes in the talents table *is* an answer, and
 * it is zero.
 */
export function statsFromSheetHtml(html: string): Partial<Record<HeroStatField, number>> {
  if (!html.slice(0, MARKER_WINDOW).includes(MARKER)) return {};

  const stats: Partial<Record<HeroStatField, number>> = {};

  for (const cells of rowsOfFirstTable(html, "characteristics-collapse")) {
    if (cells.length < 2) continue;

    // The value is in the first column and the name in the second, which is the
    // one thing about this table that cannot be assumed from the row alone: the
    // last row of it is a total, written the other way round —
    // `Total Characteristic Points | 85`. Requiring the second cell to name a
    // characteristic *and* the first to be a number throws that row out, and
    // with it the header row.
    const field = FIELD_BY_LABEL.get(cells[1]!);
    if (!field) continue;

    const value = valueOf(cells[0]!);
    if (value === null) continue;

    // SPD and BODY are printed twice on these sheets, in the primary block and
    // again lower down. They have always agreed; the first is the answer if they
    // ever stop.
    stats[field] ??= value;
  }

  // INIT is not a characteristic on the sheet at all — it is a talent, and this
  // is the one that grants it.
  stats.initiative = 0;
  for (const cells of rowsOfFirstTable(html, "talents-collapse")) {
    const found = cells[0] ? LIGHTNING_REFLEXES.exec(cells[0]) : null;
    if (found) {
      stats.initiative = Number(found[1]);
      break;
    }
  }

  return stats;
}
