/**
 * Reading a character's characteristics off the sheet it arrives on.
 *
 * The fixtures here are cut down from real exports, and each one is a shape the
 * real files actually contain rather than a shape somebody imagined: the total
 * row written back to front, a characteristic printed twice, a talent whose name
 * starts with the same word as the one that matters, and the values HERO writes
 * as fractions or pairs. Every one of them broke a simpler reading of the table.
 */

import { describe, expect, test } from "bun:test";
import { statsFromSheetHtml } from "../src/lib/sheet-stats.ts";

const MARKER = "<!--\n\nGenerated by Ork HERO Templates\n\nVersion: 1.1.0\n\n-->\n";

/** A sheet's characteristics table, from `[value, name]` pairs. */
function characteristics(...rows: [string, string][]): string {
  return `
    <div id="characteristics-collapse" class="collapse show">
      <table class="table table-sm">
        <thead><tr><th>Value</th><th>Characteristic</th><th>Base</th></tr></thead>
        <tbody>
          ${rows.map(([value, name]) => `
            <tr>
              <td><span class="primary">${value}</span></td>
              <td>${name}</td>
              <td>10</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
    </div>
  `;
}

/** A sheet's talents table, one row per talent. */
function talents(...names: string[]): string {
  return `
    <div id="talents-collapse" class="collapse show">
      <table class="table table-sm">
        <tbody>
          ${names.map((name) => `<tr><td>${name}&nbsp;</td><td class="text-end">5</td></tr>`).join("")}
        </tbody>
      </table>
    </div>
  `;
}

/** The six a full sheet carries, in the order the table prints them. */
const FULL: [string, string][] = [
  ["10", "STR"],
  ["23", "DEX"],
  ["10", "CON"],
  ["10", "BODY"],
  ["4", "SPD"],
  ["8", "REC"],
  ["30", "END"],
  ["30", "STUN"],
];

describe("a sheet that says what it is", () => {
  test("gives up its characteristics", () => {
    const stats = statsFromSheetHtml(MARKER + characteristics(...FULL));

    expect(stats).toMatchObject({
      dexterity: 23,
      body: 10,
      speed: 4,
      recovery: 8,
      endurance: 30,
      stun: 30,
    });
    // STR and CON are in the table and are not among the seven this app keeps.
    expect(Object.keys(stats).sort()).toEqual(
      ["body", "dexterity", "endurance", "initiative", "recovery", "speed", "stun"],
    );
  });

  test("and nothing at all without the marker", () => {
    // The same table, from a file that never claimed to be one of these. The ids
    // could mean anything, and a wrong reading writes silently onto a character.
    expect(statsFromSheetHtml(characteristics(...FULL))).toEqual({});
  });

  test("even when the marker is further down than the top of the file", () => {
    const buried = `<p>${"x".repeat(8000)}</p>\n${MARKER}` + characteristics(...FULL);
    expect(statsFromSheetHtml(buried)).toEqual({});
  });
});

describe("the rows a naive reading gets wrong", () => {
  test("the total is written back to front and is not a characteristic", () => {
    // The last row of every real table: a label first and a number second, where
    // every other row is the other way round. Read by position alone this invents
    // a characteristic called `85`.
    const stats = statsFromSheetHtml(
      MARKER + characteristics(["4", "SPD"], ["Total Characteristic Points", "85"]),
    );

    expect(stats.speed).toBe(4);
    expect(Object.values(stats)).not.toContain(85);
  });

  test("a characteristic printed twice is taken from the first printing", () => {
    // SPD and BODY appear in the primary block and again lower down. They have
    // always agreed on a real sheet; this is the answer if they ever stop.
    const stats = statsFromSheetHtml(
      MARKER + characteristics(["4", "SPD"], ["10", "BODY"], ["7", "SPD"]),
    );

    expect(stats.speed).toBe(4);
  });

  test("a value written as a pair is read as the first half of it", () => {
    // `6 / 16` is the characteristic and what it comes to with something else
    // switched on. The characteristic is the half this app stores.
    const stats = statsFromSheetHtml(MARKER + characteristics(
      ["6 / 16", "REC"],
      ["30/45", "STUN"],
    ));

    expect(stats).toMatchObject({ recovery: 6, stun: 30 });
  });

  test("values HERO does not write as whole numbers are left out", () => {
    // A fraction, a distance and an empty cell — all real, all in the table
    // being scanned, none of them a number this app could store. The distance is
    // a pair like the one above, but its first half is `6"` rather than a number.
    const stats = statsFromSheetHtml(MARKER + characteristics(
      ["7.666666666666667", "DEX"],
      ['6"/3"', "END"],
      ["", "STUN"],
      ["12", "BODY"],
    ));

    expect(stats).toMatchObject({ body: 12 });
    expect(stats.dexterity).toBeUndefined();
    expect(stats.endurance).toBeUndefined();
    expect(stats.stun).toBeUndefined();
  });
});

describe("INIT, which is a talent rather than a characteristic", () => {
  test("comes from Lightning Reflexes on all actions", () => {
    const stats = statsFromSheetHtml(
      MARKER + characteristics(...FULL)
      + talents("Ambidexterity", "Lightning Reflexes: +4 DEX to act first with All Actions"),
    );

    expect(stats.initiative).toBe(4);
  });

  test("is not read off the talent that merely starts the same way", () => {
    // `Lightning Calculator` is on three of the sheets this was built against.
    // Matching the name rather than the whole phrase invents an initiative bonus.
    const stats = statsFromSheetHtml(
      MARKER + characteristics(...FULL) + talents("Lightning Calculator", "Eidetic Memory"),
    );

    expect(stats.initiative).toBe(0);
  });

  test("nor off a Lightning Reflexes bought for one kind of action", () => {
    // Bought narrowly it is not a bonus the whole fight can be ordered by, so it
    // is not the initiative this app means.
    const stats = statsFromSheetHtml(
      MARKER + characteristics(...FULL)
      + talents("Lightning Reflexes: +3 DEX to act first with Ranged attacks"),
    );

    expect(stats.initiative).toBe(0);
  });

  test("and is zero on a sheet with no talents table at all", () => {
    // Five of the thirteen real sheets have no talents block. No Lightning
    // Reflexes is not a missing answer — in HERO it is the answer, and it is nil.
    const stats = statsFromSheetHtml(MARKER + characteristics(...FULL));

    expect(stats.initiative).toBe(0);
  });
});
